# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPGLIB_Main <- function(x, y, type, G, include_intercept, alpha_s, alpha_d, lambda_sparsity, lambda_diversity, tolerance, max_iter) {
    .Call('_CPGLIB_CPGLIB_Main', PACKAGE = 'CPGLIB', x, y, type, G, include_intercept, alpha_s, alpha_d, lambda_sparsity, lambda_diversity, tolerance, max_iter)
}

CV_CPGLIB_Main <- function(x, y, type, G, full_diversity, include_intercept, alpha_s, alpha_d, n_lambda_sparsity, n_lambda_diversity, tolerance, max_iter, n_folds, n_threads) {
    .Call('_CPGLIB_CV_CPGLIB_Main', PACKAGE = 'CPGLIB', x, y, type, G, full_diversity, include_intercept, alpha_s, alpha_d, n_lambda_sparsity, n_lambda_diversity, tolerance, max_iter, n_folds, n_threads)
}

CV_ProxGrad_Main <- function(x, y, type, include_intercept, alpha_s, n_lambda_sparsity, tolerance, max_iter, n_folds, n_threads) {
    .Call('_CPGLIB_CV_ProxGrad_Main', PACKAGE = 'CPGLIB', x, y, type, include_intercept, alpha_s, n_lambda_sparsity, tolerance, max_iter, n_folds, n_threads)
}

ProxGrad_Main <- function(x, y, type, include_intercept, alpha_s, lambda_sparsity, tolerance, max_iter) {
    .Call('_CPGLIB_ProxGrad_Main', PACKAGE = 'CPGLIB', x, y, type, include_intercept, alpha_s, lambda_sparsity, tolerance, max_iter)
}

